### ISSUE TITLE
Can't run adex-node locally

### ISSUE THREAD

**Issue by saimoomsafayet** [AdExNetwork/adex-node#3]
After running adex-node using **nodemon app.js** command, the following error has occured: 

```
MongoDb connection error { MongoNetworkError: connection 5 to testcluster0-shard-00-00-xy29f.mongodb.net:27017 closed
    at TLSSocket.<anonymous> (/media/saimoom/E882FD4982FD1D2E/Workspace/playground/adex-node-master/node_modules/mongodb-core/lib/connection/connection.js:276:9)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:567:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
undefined: undefined, 0x912b8f85E28B9ec196b48228159E2f13546836e6
```

Am I missing something?

**Comment by Ivshti** [comment]
you need to override those env vars to point to a local mongodb node: https://github.com/AdExNetwork/adex-node/blob/master/mongoConnection.js#L5

**Comment by saimoomsafayet** [comment]
> you need to override those env vars to point to a local mongodb node: https://github.com/AdExNetwork/adex-node/blob/master/mongoConnection.js#L5

Thanks! Another issue is how to enable developer mode for purchasing adex token? I mean to test the bidding system locally without using real ethereum? I tried using test net on MetaMask but the login is not working while on test network. TIA.

**Comment by saimoomsafayet** [comment]
> you need to override those env vars to point to a local mongodb node: https://github.com/AdExNetwork/adex-node/blob/master/mongoConnection.js#L5

Thanks. Another question is how to enable local testing of bidding without purchasing ADX token? I am trying to do that using a test network in MetaMask but while on test network the login is not working.
